management.endpoints.web.exposure.include: '*'
server.port: '8090'
course:
   message: "Hello world!!"
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
       
    h2:
      console.enabled: true